<?php

/**
 * @file
 * The farmOS Grazing Plan module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\farm_grazing_plan\Bundle\GrazingEvent;

/**
 * Implements hook_help().
 */
function farm_grazing_plan_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  // Add a link to the Movement quick form on the "Add grazing event" form, if
  // the module is installed.
  if ($route_name == 'farm_grazing_plan.add_event' && \Drupal::moduleHandler()->moduleExists('farm_quick_movement')) {
    $quick_movement_url = Url::fromRoute('farm.quick.movement', ['plan' => $route_match->getParameter('plan')->id()])->toString();
    $output .= '<p>' . t('Tip: Use the <a href=":url">Movement quick form</a> to create a movement log. You will be redirected back here to fill in more details for the plan.', [':url' => $quick_movement_url]) . '</p>';
  }

  return $output;
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function farm_grazing_plan_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['plan_record']['grazing_event'])) {
    $bundles['plan_record']['grazing_event']['class'] = GrazingEvent::class;
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function farm_grazing_plan_plan_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  /** @var \Drupal\plan\Entity\PlanInterface $entity */

  // If this is not a grazing plan in full view mode, bail.
  if (!($entity->bundle() == 'grazing' && $view_mode == 'full')) {
    return;
  }

  // If there are no grazing event, bail.
  if (empty(\Drupal::service('farm_grazing_plan')->getGrazingEvents($entity))) {
    return;
  }

  // Render the grazing plan timeline.
  $build['grazing_plan_timeline'] = \Drupal::formBuilder()->getForm('Drupal\farm_grazing_plan\Form\GrazingPlanTimelineForm', $entity);
}

/**
 * Implements hook_farm_ui_theme_region_items().
 */
function farm_grazing_plan_farm_ui_theme_region_items(string $entity_type) {

  // Position the grazing plan timeline in the top region.
  if ($entity_type == 'plan') {
    return [
      'top' => [
        'grazing_plan_timeline',
      ],
    ];
  }
  return [];
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function farm_grazing_plan_form_plan_record_grazing_event_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Hide plan and log fields in grazing_event edit forms.
  if (!empty($form['plan'])) {
    $form['plan']['#access'] = FALSE;
  }
  if (!empty($form['log'])) {
    $form['log']['#access'] = FALSE;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function farm_grazing_plan_form_quick_form_movement_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Alter the movement quick form, if a grazing plan was specified.
  $plan_id = \Drupal::request()->query->get('plan');
  if (empty($plan_id)) {
    return;
  }
  /** @var \Drupal\plan\Entity\PlanInterface|null $plan */
  $plan = \Drupal::entityTypeManager()->getStorage('plan')->load($plan_id);
  if (is_null($plan) || $plan->bundle() !== 'grazing') {
    return;
  }

  // Save the plan ID.
  $form['plan_id'] = [
    '#type' => 'value',
    '#value' => $plan->id(),
  ];

  // Add a submit function that will redirect to the "Add grazing event" form
  // with the new log pre-populated.
  $form['#submit'][] = 'farm_grazing_plan_movement_quick_form_submit';
}

/**
 * Movement quick form submit function.
 */
function farm_grazing_plan_movement_quick_form_submit(array $form, FormStateInterface $form_state) {

  // Find the log that was just created.
  $log_id = \Drupal::database()->query("SELECT entity_id FROM {log__quick} WHERE quick_value = 'movement' ORDER BY entity_id DESC LIMIT 1")->fetchField();

  // Redirect to the "Add grazing event" form with the log ID pre-populated.
  $form_state->setRedirect('farm_grazing_plan.add_event', ['plan' => $form_state->getValue('plan_id')], ['query' => ['log' => $log_id]]);
}

// Alter movement log and add a checkbox: "Update future logs for these assets"